prooph_event_store:
    stores:
        default:
            event_store: 'app.event_store.default'

services:
    _defaults:
        public: false

    Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator: ~

    in_memory_event_store:
        class: Prooph\EventStore\InMemoryEventStore

    app.event_store.default: "@in_memory_event_store"
