prooph_event_store:
    stores:
        default:
            event_store: 'app.event_store.default'
    projection_managers:
        default:
            event_store: 'app.event_store.default'
            connection: 'app.event_store.pdo_connection.mysql'
            projections:
                todo:
                    read_model: App\Read\Model\TodoReadModel
                    projection: App\Read\Projector\TodoProjector



services:
    _defaults:
        public: false

    Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator: ~

#    in_memory_event_store:
#        class: Prooph\EventStore\InMemoryEventStore

#    app.event_store.default: "@in_memory_event_store"
    
